### PR TITLE
Simple onPaste

### PR DESCRIPTION
**Pull request by RobinDev**
it's import a list on paste (if the list is nested, it's not yet managed)

most of the code come from @editorjs/list

### CODE REVIEW

**Review by neSpecc — CHANGES_REQUESTED** [review]
Please format the code using our code style. And lint it via ESLint

**Comment by RobinDev** [comment]
Wich code formatter are you using and where are the rules ?

**Comment by RobinDev** [comment]
I dig from the https://github.com/codex-team/editor.js/ config, but it was not clear to me who you apply code formatting.

**Comment by dfrankow** [comment]
Any movement on this? We'd like onPaste as well.

**Comment by robonetphy** [comment]
@RobinDev thanks for PR but the updated solution merged using pr #45. 
Pls reopen the pr if the updated changes are not the same.

**Pull request closed without merging**
