### PR TITLE
Add config options for default list style

### PR DESCRIPTION
**Pull request by leorott**
This PR adds the option to configure the default list style like this:
```
config: {
   defaultStyle: 'unordered'
}
```

### CODE REVIEW

**Review by PranaytheSingh — APPROVED** [review]
This looks good to me, thanks for adding.

**Comment by robonetphy** [comment]
@leorott Thanks for PR can you resolve the conflicts and update the `package.json` minor version so we are ready to merge or give me access to push into your fork so I can complete this PR.

**Comment by leorott** [comment]
Hi @robonetphy
I removed all conflicts 🙌

**Comment by robonetphy** [comment]
@leorott thanks for the PR, but this feature is updated via #50

**Pull request closed without merging**
